// SPDX-License-Identifier: GPL-2.0
// Copyright (C) 2020-2022 Martin Whitaker.
// Copyright (C) 2004-2026 Sam Demeulemeester.
//
// Moving inversions test with a pseudo-random sequence.
//
// Memory is filled with a vector-wide pseudo-random sequence (each vector
// lane runs an independent xorshift stream), then checked and complemented
// walking up, then checked and restored walking down, in classic moving
// inversions order. Every fourth round broadcasts a single random value to
// all lanes, preserving the uniform-background fault model of the classic
// single-pattern moving inversions test.
//
// On x86_64 the fill and check loops use AVX2 (256-bit) or SSE2 (128-bit)
// kernels with non-temporal stores, selected at runtime from the SIMD tier
// detected by simd_init(). Non-temporal stores bypass the cache and avoid
// read-for-ownership traffic, roughly doubling the write-side stress on the
// memory bus. The kernels live in tests/x86/mov_inv_rng_*.c; other builds
// use the scalar kernels below, which implement the same algorithm.
//
// The check passes regenerate the sequence instead of storing it: xorshift
// is an invertible linear map, so the descending pass simply steps the lane
// states backwards.
//
// Note: chunks are aligned to the vector size, so up to (num_cpus * vector
// size - word size) bytes per segment are not covered by this test (the same
// trade-off as the block move test). Stray words at unaligned segment edges
// are covered with a scalar round constant.
//
// SIMD dispatch approach inspired by earlier experimental work by
// Lionel Debroux.

#include <stdbool.h>
#include <stdint.h>

#include "cpuid.h"
#include "simd.h"
#include "tsc.h"

#include "display.h"
#include "error.h"
#include "test.h"

#include "test_funcs.h"
#include "test_helper.h"

#include "mov_inv_rng.h"

//------------------------------------------------------------------------------
// Pseudo-random sequence generation
//------------------------------------------------------------------------------

// Arbitrary distinct constants used to decorrelate the per-lane xorshift
// streams seeded from a single per-round seed.
#if TESTWORD_WIDTH > 32
static const testword_t lane_salt[VEC_LANES] = {
    UINT64_C(0x9e3779b97f4a7c15),
    UINT64_C(0xbf58476d1ce4e5b9),
    UINT64_C(0x94d049bb133111eb),
    UINT64_C(0x2545f4914f6cdd1d)
};
#else
static const testword_t lane_salt[VEC_LANES] = {
    0x9e3779b9,
    0xbf58476d,
    0x94d049bb,
    0x2545f491
};
#endif

// Inverts one y = x ^ (x << shift) step of the xorshift generator.
static inline testword_t prsg_undo_lshift(testword_t y, int shift)
{
    testword_t x = y;
    testword_t t = y;

    for (int k = shift; k < TESTWORD_WIDTH; k += shift) {
        t <<= shift;
        x ^= t;
    }
    return x;
}

// Inverts one y = x ^ (x >> shift) step of the xorshift generator.
static inline testword_t prsg_undo_rshift(testword_t y, int shift)
{
    testword_t x = y;
    testword_t t = y;

    for (int k = shift; k < TESTWORD_WIDTH; k += shift) {
        t >>= shift;
        x ^= t;
    }
    return x;
}

// Returns the previous word in the pseudo-random sequence generated by prsg().
static inline testword_t prsg_inverse(testword_t state)
{
#if TESTWORD_WIDTH > 32
    state = prsg_undo_lshift(state, 17);
    state = prsg_undo_rshift(state, 7);
    state = prsg_undo_lshift(state, 13);
#else
    state = prsg_undo_lshift(state, 5);
    state = prsg_undo_rshift(state, 17);
    state = prsg_undo_lshift(state, 13);
#endif
    return state;
}

// Initialises the lane states from the per-round seed. For splat rounds all
// lanes hold the same value and are never stepped, giving a uniform background.
static void seed_lanes(vec_state_t *st, testword_t seed, bool splat)
{
    if (splat) {
        testword_t s = seed != 0 ? seed : lane_salt[0];
        s = prsg(s);
        for (int l = 0; l < VEC_LANES; l++) {
            st->lane[l] = s;
        }
    } else {
        for (int l = 0; l < VEC_LANES; l++) {
            testword_t s = seed ^ lane_salt[l];
            if (s == 0) {
                s = lane_salt[l];
            }
            st->lane[l] = prsg(s);
        }
    }
}

//------------------------------------------------------------------------------
// Scalar kernels (all architectures)
//
// These process nblocks whole vector blocks starting at p (the descending
// check processes them from the top down). The lane states are carried in
// memory between invocations, so no SIMD state is live across calls to
// data_error(), do_tick(), or the thread barriers.
//------------------------------------------------------------------------------

static void vec_fill_scalar(vec_state_t *st, testword_t *p, size_t nblocks, bool splat)
{
    for (size_t k = 0; k < nblocks; k++) {
        for (int l = 0; l < VEC_LANES; l++) {
            write_word(&p[l], st->lane[l]);
        }
        p += VEC_LANES;
        if (!splat) {
            for (int l = 0; l < VEC_LANES; l++) {
                st->lane[l] = prsg(st->lane[l]);
            }
        }
    }
}

static void vec_check_fwd_scalar(vec_state_t *st, testword_t *p, size_t nblocks, bool splat)
{
    for (size_t k = 0; k < nblocks; k++) {
        for (int l = 0; l < VEC_LANES; l++) {
            testword_t expect = st->lane[l];
            testword_t actual = read_word(&p[l]);
            if (unlikely(actual != expect)) {
                data_error(&p[l], expect, actual, true);
            }
            write_word(&p[l], ~expect);
        }
        p += VEC_LANES;
        if (!splat) {
            for (int l = 0; l < VEC_LANES; l++) {
                st->lane[l] = prsg(st->lane[l]);
            }
        }
    }
}

static void vec_check_rev_scalar(vec_state_t *st, testword_t *p, size_t nblocks, bool splat)
{
    for (size_t k = nblocks; k-- > 0; ) {
        testword_t *q = p + k * VEC_LANES;
        if (!splat) {
            for (int l = 0; l < VEC_LANES; l++) {
                st->lane[l] = prsg_inverse(st->lane[l]);
            }
        }
        for (int l = 0; l < VEC_LANES; l++) {
            testword_t expect = ~st->lane[l];
            testword_t actual = read_word(&q[l]);
            if (unlikely(actual != expect)) {
                data_error(&q[l], expect, actual, true);
            }
            write_word(&q[l], st->lane[l]);
        }
    }
}

//------------------------------------------------------------------------------
// Kernel dispatch
//------------------------------------------------------------------------------

static void vec_fill(vec_state_t *st, testword_t *p, size_t nblocks, bool splat)
{
#if defined(__x86_64__)
    if (simd_tier == SIMD_AVX2) {
        vec_fill_avx2(st, p, nblocks, splat);
        return;
    }
    if (simd_tier == SIMD_SSE2) {
        vec_fill_sse2(st, p, nblocks, splat);
        return;
    }
#endif
    vec_fill_scalar(st, p, nblocks, splat);
}

static void vec_check_fwd(vec_state_t *st, testword_t *p, size_t nblocks, bool splat)
{
#if defined(__x86_64__)
    if (simd_tier != SIMD_NONE) {
        while (nblocks > 0) {
            size_t done = (simd_tier == SIMD_AVX2) ? vec_scan_fwd_avx2(st, p, nblocks, splat)
                                                   : vec_scan_fwd_sse2(st, p, nblocks, splat);
            p += done * VEC_LANES;
            nblocks -= done;
            if (nblocks == 0) {
                break;
            }
            // The scan stopped at a mismatching block. Report and fix it up,
            // then resume the scan on the remaining blocks.
            vec_check_fwd_scalar(st, p, 1, splat);
            p += VEC_LANES;
            nblocks--;
        }
        return;
    }
#endif
    vec_check_fwd_scalar(st, p, nblocks, splat);
}

static void vec_check_rev(vec_state_t *st, testword_t *p, size_t nblocks, bool splat)
{
#if defined(__x86_64__)
    if (simd_tier != SIMD_NONE) {
        testword_t *q = p + (nblocks - 1) * VEC_LANES;
        while (nblocks > 0) {
            size_t done = (simd_tier == SIMD_AVX2) ? vec_scan_rev_avx2(st, q, nblocks, splat)
                                                   : vec_scan_rev_sse2(st, q, nblocks, splat);
            q -= done * VEC_LANES;
            nblocks -= done;
            if (nblocks == 0) {
                break;
            }
            // The scan stopped at a mismatching block, with the lane states
            // already stepped back to it. Report and fix it up, then resume.
            // Unlike the forward case, the scalar kernel cannot be reused
            // here as it would step the lane states back a second time.
            for (int l = 0; l < VEC_LANES; l++) {
                testword_t expect = ~st->lane[l];
                testword_t actual = read_word(&q[l]);
                if (unlikely(actual != expect)) {
                    data_error(&q[l], expect, actual, true);
                }
                write_word(&q[l], st->lane[l]);
            }
            q -= VEC_LANES;
            nblocks--;
        }
        return;
    }
#endif
    vec_check_rev_scalar(st, p, nblocks, splat);
}

//------------------------------------------------------------------------------
// Public Functions
//------------------------------------------------------------------------------

int test_mov_inv_rng(int my_cpu, bool splat_round)
{
    int ticks = 0;

    testword_t seed;
    if (cpuid_info.flags.rdtsc) {
        seed = get_tsc();
    } else {
        seed = 1 + pass_num;
    }
    seed *= 0x12345678;

    vec_state_t st;
    seed_lanes(&st, seed, splat_round);

    // Round constant used for stray words at unaligned segment edges.
    testword_t epat = st.lane[0];

    if (my_cpu == master_cpu) {
        display_test_pattern_value(st.lane[0]);
    }

    // Initialize memory with the pseudo-random sequence.
    for (int j = 0; j < vm_map_size; j++) {
        testword_t *start, *end;
        calculate_chunk(&start, &end, my_cpu, j, VEC_BYTES);
        if (end < start) SKIP_RANGE(1)  // we need at least one word for this test

        // Split the chunk into an aligned vector body and stray edge words.
        testword_t *bstart = (testword_t *)round_up((uintptr_t)start, VEC_BYTES);
        size_t nwords = (bstart <= end) ? (size_t)(end - bstart) + 1 : 0;
        size_t nbody  = nwords - nwords % VEC_LANES;

        if (my_cpu >= 0) {
            for (testword_t *q = start; q < bstart && q <= end; q++) {
                write_word(q, epat);
            }
            for (testword_t *q = bstart + nbody; q <= end; q++) {
                write_word(q, epat);
            }
        }
        if (nbody == 0) SKIP_RANGE(1)

        testword_t *bend = bstart + (nbody - 1);

        testword_t *p  = bstart;
        testword_t *pe = bstart;

        bool at_end = false;
        do {
            // take care to avoid pointer overflow
            if ((bend - pe) >= SPIN_SIZE) {
                pe += SPIN_SIZE - 1;
            } else {
                at_end = true;
                pe = bend;
            }
            ticks++;
            if (my_cpu < 0) {
                continue;
            }
            test_addr[my_cpu] = (uintptr_t)p;
            vec_fill(&st, p, ((size_t)(pe - p) + 1) / VEC_LANES, splat_round);
            p = pe + 1;
            do_tick(my_cpu);
            BAILOUT;
        } while (!at_end && ++pe); // advance pe to next start point
    }

    // Check for the pattern and write the complement for each memory location,
    // walking up. The sequence is regenerated from the seed.
    flush_caches(my_cpu);

    seed_lanes(&st, seed, splat_round);

    for (int j = 0; j < vm_map_size; j++) {
        testword_t *start, *end;
        calculate_chunk(&start, &end, my_cpu, j, VEC_BYTES);
        if (end < start) SKIP_RANGE(1)  // we need at least one word for this test

        testword_t *bstart = (testword_t *)round_up((uintptr_t)start, VEC_BYTES);
        size_t nwords = (bstart <= end) ? (size_t)(end - bstart) + 1 : 0;
        size_t nbody  = nwords - nwords % VEC_LANES;

        if (my_cpu >= 0) {
            for (testword_t *q = start; q < bstart && q <= end; q++) {
                testword_t actual = read_word(q);
                if (unlikely(actual != epat)) {
                    data_error(q, epat, actual, true);
                }
                write_word(q, ~epat);
            }
            for (testword_t *q = bstart + nbody; q <= end; q++) {
                testword_t actual = read_word(q);
                if (unlikely(actual != epat)) {
                    data_error(q, epat, actual, true);
                }
                write_word(q, ~epat);
            }
        }
        if (nbody == 0) SKIP_RANGE(1)

        testword_t *bend = bstart + (nbody - 1);

        testword_t *p  = bstart;
        testword_t *pe = bstart;

        bool at_end = false;
        do {
            // take care to avoid pointer overflow
            if ((bend - pe) >= SPIN_SIZE) {
                pe += SPIN_SIZE - 1;
            } else {
                at_end = true;
                pe = bend;
            }
            ticks++;
            if (my_cpu < 0) {
                continue;
            }
            test_addr[my_cpu] = (uintptr_t)p;
            vec_check_fwd(&st, p, ((size_t)(pe - p) + 1) / VEC_LANES, splat_round);
            p = pe + 1;
            do_tick(my_cpu);
            BAILOUT;
        } while (!at_end && ++pe); // advance pe to next start point
    }

    // Check for the complement and restore the pattern for each memory
    // location, walking down. The lane states are stepped backwards, so no
    // stored sequence is needed.
    flush_caches(my_cpu);

    for (int j = vm_map_size - 1; j >= 0; j--) {
        testword_t *start, *end;
        calculate_chunk(&start, &end, my_cpu, j, VEC_BYTES);
        if (end < start) SKIP_RANGE(1)  // we need at least one word for this test

        testword_t *bstart = (testword_t *)round_up((uintptr_t)start, VEC_BYTES);
        size_t nwords = (bstart <= end) ? (size_t)(end - bstart) + 1 : 0;
        size_t nbody  = nwords - nwords % VEC_LANES;

        if (my_cpu >= 0) {
            for (testword_t *q = bstart + nbody; q <= end; q++) {
                testword_t actual = read_word(q);
                if (unlikely(actual != (testword_t)~epat)) {
                    data_error(q, ~epat, actual, true);
                }
                write_word(q, epat);
            }
        }
        if (nbody == 0) {
            if (my_cpu >= 0) {
                for (testword_t *q = start; q < bstart && q <= end; q++) {
                    testword_t actual = read_word(q);
                    if (unlikely(actual != (testword_t)~epat)) {
                        data_error(q, ~epat, actual, true);
                    }
                    write_word(q, epat);
                }
            }
            SKIP_RANGE(1)
        }

        testword_t *bend = bstart + (nbody - 1);

        testword_t *p  = bend;
        testword_t *ps = bend;

        bool at_start = false;
        do {
            // take care to avoid pointer underflow
            if ((ps - bstart) >= SPIN_SIZE) {
                ps -= SPIN_SIZE - 1;
            } else {
                at_start = true;
                ps = bstart;
            }
            ticks++;
            if (my_cpu < 0) {
                continue;
            }
            test_addr[my_cpu] = (uintptr_t)ps;
            vec_check_rev(&st, ps, ((size_t)(p - ps) + 1) / VEC_LANES, splat_round);
            p = ps - 1;
            do_tick(my_cpu);
            BAILOUT;
        } while (!at_start && --ps); // advance ps to next start point

        if (my_cpu >= 0) {
            for (testword_t *q = start; q < bstart && q <= end; q++) {
                testword_t actual = read_word(q);
                if (unlikely(actual != (testword_t)~epat)) {
                    data_error(q, ~epat, actual, true);
                }
                write_word(q, epat);
            }
        }
    }

    return ticks;
}
